pytech_bookstore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("store/", include("store.urls", namespace="store")),
    path("user/", include("user.urls", namespace="user")),
]

store/urls.py
# store/urls.py
from django.urls import path
from .views import index, AuthorListView, BookListView

app_name = "store"

urlpatterns = [
    path("", index, name="home"),
    path("author/", AuthorListView.as_view(), name="author_list"),
    path('books/', BookListView.as_view(), name='book_list'),
]

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("register/", views.user_registration, name="register"),
    path("login/", views.Login.as_view(), name="login"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/pace.css' %}">
	    <link rel="stylesheet" href="{% static 'css/custom.css'%}">

	    <!-- js -->
	    <script src="js/jquery-2.1.3.min.js"></script>
	    <script src="js/bootstrap.min.js"></script>
	    <script src="js/pace.min.js"></script>
	    <script src="js/modernizr.custom.js"></script>
	</head>

    <body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="#"><b>Pytech</b> Bookstore</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
									{% comment %}
									{% endcomment %}
    								<li class="cl-effect-11"><a href="{% url 'store:home' %}" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="{% url 'store:book_list' %}" data-hover="Store">Store</a></li>
    								
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

        {% block content %}

        {% endblock %}

        <footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2024 Pytech</p>
					</div>
				</div>
			</div>
		</footer>
		<script src="js/script.js"></script>
		
	</body>
</html>